#!/bin/sh

find /opt/sonatype ! \( -user nexus -o -group nexus \) -exec chown nexus:nexus {} \;	
find /nexus-data   ! \( -user nexus -o -group nexus \) -exec chown nexus:nexus {} \;	
su-exec nexus /opt/sonatype/nexus/bin/nexus run